* Ham and Swiss Army Knife (hasak) keyer
**  This is a morse code keyer built for the Hermes Lite 
   low latency keyer project.  The goal is to allow
   the operator to hear keyed code with low latency
   while listening to and keying a possibly remote
   transceiver.
   This implementation of the keyer consumes around 4%
   of the Teensy4's cpu cycles in the audio library loop.
   "Sketch uses 68548 bytes (3%) of program storage space. 
   Maximum is 2031616 bytes. Global variables use 88544 bytes
   (16%) of dynamic memory, leaving 435744 bytes for local 
   variables. Maximum is 524288 bytes."
** It currently runs on a Teensy 4.0 with Teensy Audio 
   Adapter board, but it has also run on a Teensy 3.1
   with Teensy Audio Adapter.  I suspect it will work
   with limits on a plain Teensy 3 or 4.
** Hardware set up is straight forward.
   Most of this can be found in ./config.h.
   Pin 0 is the right paddle key in.
   Pin 1 is the left paddle key in.
   Pin 2 is the straight key in.
   Pin 3 is a PTT switch, as yet unused.
   Pin 4 is Key out.
   Pin 5 is PTT out.
   On the Teensy 4 only, pin 20 should be jumpered to pin 22,
     it is the I2S LRCLK signal that is used to generate a 
     sample rate interrupt.
   For a typical phone headset with microphone and button(s),
     you will need wires from audio adapter headphone L, R,
     MIC and GND, two ~220uF electrolyics to couple L and R
     to the headphones and a properly wired TRRS jack.
     (I use 100uF electrolytics.)
   Line in and line out.
   There is ouput passed to the hardware DAC.
	 On a Teensy 3.1/3.2, this is the pin labelled DAC/A14.
	 On a Teensy 3.5/3.6, the pins are labelled   A21/A22.
	 On a Teensy 4.0, the pins are labelled 10/12.
** The keyer is currently configured as a keyer.
   The RX audio coming in over usb is mixed with locally generated
   sidetone and played over the headphones. You can configure the
   keying parameters in the ctrlr panel. If you enable TX on the 
   ctrlr panel then the keyer can send:
   keyed IQ as usb audio, if IQ is enabled,
   MIDI note on/off events as usb MIDI, if send midi is enabled,
   and produce CMOS key_out and ptt_out on pins 4 and 5.
* To build the keyer
** You need the Arduino IDE with the Teensyduino extensions.  
   Consult pjrc.com for details.
** Build the keyer with the proper board entry.
** Specify the  proper board in the Tools > Board > Teensyduino menu
** Specify USB Type to be Serial+MIDI+Audio
** Compile and download.
* The keyer should start operating immediately.
  It will use the default settings that were compiled.
  It should produce sidetone for straight key and iambic
  mode A at 18 WPM for the paddle.
* Parameters can be changed with MIDI.   
** The file ctrlr/hasak.panel is a panel definition for Ctrlr,
   a MIDI control panel program.  
** You can download Ctrlr from https://ctrlr.org/nightly/?C=M;O=D,
   I only use the 5.3.201 release, later versions have issues.
*** If you run Ctrlr on linux, be sure to vist Edit> Preferences
    and uncheck "Use OS native file open/save dialogs ..."
** Run Ctrlr with the panel definition as its only argument.
** The panel lays out the parameters that can be changed
   while the keyer is running.
** Several issues have yet to be resolved,
   the current but somewhat outdated list can be found in doc/ToDo.org
* Known problems
** ptt_head isn't working.
** The earphones make a loud pop when the codec is enabled.
   It doesn't happen if you use the headphone jack on the audio
   adapter.
* Don't forget
** Teensy 4 pin 20 jumpered to pin 22.
** Don't connect the audio adapter headphone jack shield/ground pad
   to anything, it's a virtual ground biased at ~1.55V.
** Have fun.
-- 73 -- rec -- ad5dz --
