* Restarting activity as of 2024-12-19
** The KEY/PTT_OUT issues should be solved.
   But I haven't tested the last fix.
** Adding the LED support
   put a string of NeoPixels on the top cap to signal status
   and provide a visual morse depiction.
   It turns out that Stoffregen has a non-blocking neopixel library,
   https://github.com/PaulStoffregen/WS2812Serial, but it needs a
   serial interface to work.  It translates the NeoPixel bitstream
   into a serial bitstream and transmits the bits with DMA.
** The footprint of the QRP Labs low pass and band pass filters
   will fit onto a hasak shield.  So if I can build an SI5351A
   VFO and Tayloe detector on a hasak shield, then I add a plug-in
   bandpass filter; and if I can build a CW xmtr on a shield, then I
   can add a plug-in low pass filter.
** On the PD interface, there are many micro B plugs that could be
   tried to inject the usb data lines.
* Restarting activity as of 2024-12-14
  Several mistakes in the code
** PTT_OUT is on pin 4, wired to socket ring, white wire on TRS cable
** KEY_OUT is on pin 5, wired to socket tip, red wire on TRS cable
** PTT_OUT and KEY_OUT pins are logic active high when driving the
   opto-isolator, which becomes active low when seen at the HL2 input.
** So the first hasak shield has the KEY/PTT/OUT pins reversed, but the
   signals go to the correct pins, 
** Fix
*** put PTT_OUT and KEY_OUT on the correct pins for the CWKeyerShield
    This worked after several reshuffles of various mistakes, I had
    uncrossed the lines more than once.
*** swap the T and R on the output cable of the initial hasak shield
    This is strike 7 against the 1mm pitch connector, just try and unsolder
    and resolder it, time to retire this hasak shield and put another in service.
    Except I don't want to resolder all those cables again, so just cut the two
    wires and butt solder them together.
*** swap the output wiring on the prototype
    and see if active low logic is enough to key the HL2.  It is, but it also
    keys when you unplug the usb interface from hasak.
*** installing 2N7000s on proto would allow it to function in same logic
    as the opto-isolator.
*** adding 0.001µF bypass caps would short RF to ground on all digital inputs 
    and outputs
*** adding 470 ohm resistor, not sure what its purpose is
** Need a page in hasak.elf.org to set all parameters, need to flip the
   logic of the PTT_OUT and KEY_OUT depending on whether we're using the
   barebones hasak shield or the CWKeyerShield.  That along might be enough
   reason to install the 2N7000's.
* Restarting activity as of 2024-09-03
* Failed to compile for lack of wm8960
  copied control_wm8960.* from CWKeyer/libraries/teensy/Audio
* Failed to install to hardware
  follow instructions to install udev rules.
* Build and runs using current Arduino and Teensyduino without
  hacks.
* sgtl5000 $3.855 / unit at jlcpcb.com, $4.65 / unit at digikey.com
* wm8960 $7.2765 / unit at jlcpcb.com, $3.70529 / unit at digikey not in stock
* ak4558 estimated $20.70 not stocked at jlcpcb.com, $4.98 / unit at digikey.com
* cs4272 $4.5660 / unit at jlcpcb.com, $11.20000 / unit at best at digikey.com
* wm8731 $9.1620 12 day lead time, not stocked at jlcpcb.com, $3.54517 / unit at digikey.com, possible per tray of 60
* cs42448 not stocked at jlcpcb.com, $9.25534 / unit not stocked at digikey.com
* wm8904 $2.8440 / unit at jlcpcb.com, $7.74 / unit at digikey.com
* cabling expected
** paddle in / TRS - pin 0 is right paddle (white ring), pin 1 is left paddle (red tip)
** key/ptt in / TRS - pin 2 is key (red tip), pin 3 is ptt (white ring)
** key/ptt out / TRS - pin 4 is key out (red tip), pin 5 is ptt out (white ring)
** MQS headphones out / TRS - pin 10 is mqsr (red tip), pin 12 is mqsl (white ring)
** speaker left / TRS (+, -, ground)
** speaker right / TRS (+, -, ground)
** headphones out / TRS
** headset in-out / TRRS
** microphone in / TRS
** line in / TRS
** line out / TRS
** paddle2 in / TRS
** key/ptt2 in / TRS
** key/ptt2 out / TRS
* Optional dial interface
** Stack5 Dial5
** I2C + 5V + PwrGnd
** Displays speed / frequency / level / time / date
** Power connector DB2EK 2 Pin
   DORABO DB2EK-2.54-2P-GN-S is a terminal block that plugs into the power connector
** I2C connector is a Grove connector, JST connectors type 'HY2.0-4P'.
